CREATE TABLE pagamentos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_external_id VARCHAR(100) NOT NULL,
    external_reference VARCHAR(150) NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    status VARCHAR(30) NOT NULL,
    status_detail VARCHAR(100),
    valor DECIMAL(10, 2) NOT NULL,
    email_pagador VARCHAR(254) NOT NULL,
    pix_copia_cola TEXT NOT NULL,
    qr_code_base64 LONGTEXT NOT NULL,
    ticket_url TEXT,
    data_expiracao DATETIME(6) NOT NULL,
    criado_em DATETIME(6) NOT NULL,
    atualizado_em DATETIME(6) NOT NULL,
    pago_em DATETIME(6),
    plano_gerado BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_pagamentos_order_external_id UNIQUE (order_external_id),
    CONSTRAINT uk_pagamentos_external_reference UNIQUE (external_reference),
    CONSTRAINT uk_pagamentos_idempotency_key UNIQUE (idempotency_key),
    INDEX idx_pagamentos_order_external_id (order_external_id),
    INDEX idx_pagamentos_external_reference (external_reference),
    INDEX idx_pagamentos_status (status)
);
